lock-scren: update to add turning off displays and suspend options

diff --git a/.local/bin/lock-screen b/.local/bin/lock-screen
--- a/.local/bin/lock-screen
+++ b/.local/bin/lock-screen
@@ -1,48 +1,120 @@
 #!/usr/bin/env bash
 
-image="$HOME/Nextcloud/Fondos de pantalla/Misty_Mountain_crop.jpg"
-background=2E3440
-current_line=4C566A
-foreground=D8DEE9
-comment=4C566A
-pink=B48EAD
-purple=88C0D0
-red=BF616A
-font="Inter Medium"
+usage() {
 
-[[ -z "$(pgrep -f ^i3lock)" ]] || exit 1
+printf "%s" "\
+usage: $(basename "$0") [options]
 
-killall -SIGUSR1 dunst
+Options:
+    -h, --help                  show this help message and exit.
+    -o, --off                   turn all displays off.
+    -s, --suspend               run systemctl suspend afterwards.
 
-i3lock \
-    --nofork \
-    --ignore-empty-password \
-    --tiling \
-    --image="$image" \
-    --clock \
-    --insidever-color=$background \
-    --insidewrong-color=$background \
-    --inside-color=$background \
-    --ringver-color=$pink \
-    --ringwrong-color=$red \
-    --ring-color=$current_line \
-    --line-uses-inside \
-    --keyhl-color=$purple \
-    --bshl-color=$comment \
-    --separator-color=$current_line \
-    --time-color=$foreground \
-    --time-str="%-H:%M" \
-    --time-pos="ix:iy-250" \
-    --date-color=$foreground \
-    --date-str="%a, %d de %b de %Y" \
-    --time-font="$font" \
-    --date-font="$font" \
-    --time-size=80 \
-    --date-size=20 \
-    --date-pos="tx:ty+40" \
-    --verif-text="" \
-    --wrong-text="" \
-    --noinput-text="" \
-    --no-modkey-text
+"
 
-killall -SIGUSR2 dunst
+exit 1
+
+}
+
+get_args() {
+    TEMP=$(getopt \
+               -l 'help,off,suspend' \
+               -o 'hos' \
+               -n "$(basename "$0")" \
+               -- "$@") || exit 1
+
+    eval set -- "$TEMP"
+    unset TEMP
+
+    while true; do
+        case "$1" in
+            '-h' | '--help')
+                usage
+            ;;
+            '-o' | '--off')
+                off=1
+                shift
+                continue
+            ;;
+            '-s' | '--suspend')
+                susp=1
+                shift
+                continue
+            ;;
+            '--')
+                shift
+                break
+            ;;
+            *)
+                printf "error\n" >&2
+                exit 1
+            ;;
+        esac
+    done
+}
+
+main() {
+    get_args "$@"
+
+    image="$HOME/Nextcloud/Fondos de pantalla/Misty_Mountain_crop.jpg"
+    background=2E3440
+    current_line=4C566A
+    foreground=D8DEE9
+    comment=4C566A
+    pink=B48EAD
+    purple=88C0D0
+    red=BF616A
+    font="Inter Medium"
+
+    [[ -z "$(pgrep -f ^i3lock)" ]] || exit 1
+
+    killall -SIGUSR1 dunst
+
+    [[ "$off" ]] && bright-notif off
+
+    i3lock \
+        --nofork \
+        --ignore-empty-password \
+        --tiling \
+        --image="$image" \
+        --clock \
+        --insidever-color=$background \
+        --insidewrong-color=$background \
+        --inside-color=$background \
+        --ringver-color=$pink \
+        --ringwrong-color=$red \
+        --ring-color=$current_line \
+        --line-uses-inside \
+        --keyhl-color=$purple \
+        --bshl-color=$comment \
+        --separator-color=$current_line \
+        --time-color=$foreground \
+        --time-str="%-H:%M" \
+        --time-pos="ix:iy-250" \
+        --date-color=$foreground \
+        --date-str="%a, %d de %b de %Y" \
+        --time-font="$font" \
+        --date-font="$font" \
+        --time-size=80 \
+        --date-size=20 \
+        --date-pos="tx:ty+40" \
+        --verif-text="" \
+        --wrong-text="" \
+        --noinput-text="" \
+        --no-modkey-text &
+
+    if [[ "$susp" ]]; then
+        sleep 0.5
+        systemctl suspend
+    fi
+
+    wait
+
+    killall -SIGUSR2 dunst
+
+    [[ "$off" ]] && xmodmap $HOME/.Xmodmap
+
+    return 0
+}
+
+main "$@"
