tabc: implement autoattach

diff --git a/.local/bin/tabc b/.local/bin/tabc
--- a/.local/bin/tabc
+++ b/.local/bin/tabc
@@ -98,9 +98,41 @@ detach() {
 }
 
 autoattach() {
-    printf "WIP\n" >&2
+    id=$1
 
-    # TODO kill/run tabbed-sub & tabbed-unsub
+    tabbedsub_parentpx=$(pgrep -fo "tabbed-sub $id")
+    tabbedunsub_parentpx=$(pgrep -fo "tabbed-unsub $id")
+
+    if [[ -z $tabbedsub_parentpx ]]; then
+        if [[ -z $tabbedunsub_parentpx ]]; then
+            tabbed-sub "$id" &
+            tabbed-unsub "$id" &
+        else
+            printf "error: subscription process found, but unsubscription process not found\n" >&2
+
+            tabbedsub_px=$(pgrep -P $tabbedsub_parentpx -f "bspc")
+
+            kill $tabbedsub_px
+
+            exit 1
+        fi
+    else
+        if [[ -z $tabbedsub_parentpx ]]; then
+            printf "error: unsubscription process found, but subscription process not found\n" >&2
+
+            tabbedunsub_px=$(pgrep -P $tabbedunsub_parentpx -f "bspc")
+
+            kill $tabbedunsub_px
+
+            exit 1
+        else
+            tabbedsub_px=$(pgrep -P $tabbedsub_parentpx -f "bspc")
+            tabbedunsub_px=$(pgrep -P $tabbedunsub_parentpx -f "bspc")
+
+            kill $tabbedsub_px
+            kill $tabbedunsub_px
+        fi
+    fi
 }
 
 get_command() {
@@ -115,7 +147,7 @@ get_command() {
             detach $(bspc query -N -n)
         ;;
         autoattach)
-            autoattach
+            autoattach $(bspc query -N -n)
         ;;
         *)
             usage
